### ISSUE TITLE
Export CSV funktioniert im merge nicht

### ISSUE THREAD

**Issue by arjunane** [wupperinst/osmTGmod#11]
Ich bin auch fast soweit, dass des nun auf allen Betriebssystemen und Python 2 und 3 funktionieren sollte. Nur der CSV-Export macht mir da gerade noch ein Strich durch die Rechnung. Da wäre es schön, wenn du den mal mit merge-Versions und einer aktuellen osm_datei ausprobierst. Mit dem alten Code unter python 2.7 funktioniert es reibungslos, aber sobald ich das mit dem neuen Code unter 3.5 oder unter 2.7 probiere hängt er sich an dem ß auf… Es wäre gut zu wissen, ob das nur an dem Betriebssystem liegt, oder ob du mit dem Code so wie er da jetzt liegt auch probleme hast.

**Comment by maltesc** [comment]
Ich habe den CSV von merge_versions auf Python 3.5.1 und LINUX getestet. Alles funktioniert problemlos. Evtl. kann man dem "Übersetzungspackage" irgendwie sagen, dass bitte der CSV-Export nicht angetastet werden soll.

**Comment by arjunane** [comment]
Hi Malte, 
ich habe nach langem hin und her herausgefunden, dass das Problem nicht Plattformspezifisch ist sondern an diversen anderen Dingen liegt.
Das wichtigste ist, dass es jetzt in Merge_Versions funktionieren sollte. Allerdings mit der Einschränkung, dass es nicht funktioniert, wenn das skript über IDLE unter python 3.5.1 aufgerufen wird. Sobald das skript über das terminal ausgeführt wird gibt es kein Problem. (Bis ich das mal raushatte...) 
Wenn das Skript über IDLE audgeführt wird, wird der Wert von sys.stdout.encoding automatisch auf ascii gesetzt. Über das terminal ausgeführt ist sys.stdout.encoding auf utf-8.
Allerdings ist die Ausführung in python 2.7 trotz dieses Wertes möglich, in python 3.5 aber nicht. Wenn du das Skript mit python 3.5 über IDLE ausführbar machen willst, müsstest du dir die Geschichte noch einmal anschauen. Ich glaube da bräuchte es noch andere Einstellung in den general functions.py

**Comment by arjunane** [comment]
Und mit dem letzten Commit soltle auch dieses Problem behoben sein. Jetzt Funktioniert es unabhängig von Betriebssystem und Pythonversion.
